### PR TITLE
Improved langauge selection functionality

### PR DESCRIPTION
**Pull request by TeaBizzy**
For issue #5: `lang_code.js`, now has functionality for user to select the languages to be translated without modifying the `langsExplain` object.

`lang_code.js` will export the selected languages, or all of them by default if none have been selected.

Comments have been added to guide the user on how to select the languages to translate.

Your feed back is appreciated. 

**PS:** _if accepted we may want to make further improvements to documentation to reflect the changes._

### CODE REVIEW

**Comment by jacobkim9881** [comment]
Appreciate the pull request. Let me accept this after having a review. 
As you mentioned users may touch the object in `lang_code.js`, which is not our intention. The array should be imported from a list of the array. Let me ask pull request to your fork.

**Comment by jacobkim9881** [comment]
Let's discuss about writing documentation in a new issue.

**Comment by TeaBizzy** [comment]
Thanks @jacobkim9881. Happy to help!

**Comment by TeaBizzy** [comment]
For issue #9. Updated the README.md documentation to support the changes in #7

**Comment by jacobkim9881** [comment]
I appreciate your pull request, @TeaBizzy. Specially editing documents is not coding. I will check and merge the pull request.

**Comment by TeaBizzy** [comment]
@jacobkim9881 your welcome. Documentation is very important. I wouldn't have been able to contribute to this project without the well written documentation you provided. In order for others to contribute it should be maintained by everyone making changes.

Thank you!

**Comment by jacobkim9881** [comment]
@TeaBizzy Like other coders do, I also am not good at writing documentaries as I am better at building code. Specially I am a foreigner as English speaker. I always try to communicate to build better code.

**Comment by jacobkim9881** [comment]
Found any error for this pull request. About the comment at line 3 in `lang_code.js`, seems leaving both the `langsToTranslate` and `langsExplain` in `lang_code.js` have more chances for users to edit `langsExplain` as you commented. I had asked to [pull request](https://github.com/TeaBizzy/localization-manager/pull/1) at your [TeaBizzy:improve-language-selector](https://github.com/TeaBizzy/localization-manager/tree/improve-language-selector) branch. Could you check and review this pull request?

**Comment by TeaBizzy** [comment]
Hi @jacobkim9881 , I completely agree with separating the 2. This will prevent further user error from editing the `langsExplain` object accidentally. 

Sorry I missed your PR. I will review it in the morning.

**Comment by jacobkim9881** [comment]
@TeaBizzy I agree with that. For users there should be only the array without any other data. It makes better convenience for users.

**Pull request merged**
